### ISSUE TITLE
Enable handling of multiple setup files

### ISSUE THREAD

**Issue by hackermd** [TissueMAPS/TmDeploy#5]
At the moment, only a single architecture can be configured at a time using the definition provided via the `setup.yml` file. The setup description could be extended to support multiple architectures. To this end, each architecture should have a separate `cloud` and `clusters` section for maximum flexibility. The name of the architecture that should be setup via `tm_deploy` would then need to be parsed via the command line.

**Comment by riccardomurri** [comment]
I think it would be better to have a separate *config file* per each architecture, rather than stuffing a single config file with all architectures.

This would allow, e.g., to distribute an "arch file" and then instruct users to run `tm_deploy -c archfile.yml` to set the cluster up.  Cf. https://github.com/gc3-uzh-ch/elasticluster/issues/332

**Comment by HackerMD** [comment]
That would be even easier to implement. We have to keep in mind that we also need to parse the `-c` option to the [dynamic Ansible inventory](https://docs.ansible.com/ansible/intro_dynamic_inventory.html) `tm_inventory`, because it builds the inventory based on the information provided via `archfile.yml`.

**Comment by hackermd** [comment]
How shall we parse the path to `archfile.yml` from `tm_deploy` to `tm_inventory`? I see two possibilities:

- Adding a new command line argument to `tm_inventory`.
- Using a environment variable that we set in `tm_deploy`.

We need to be careful to not break the functionality of the dynamic inventory, for example with regard to using [meta](https://docs.ansible.com/ansible/meta_module.html).

```yaml
meta: refresh_inventory
```

> refresh_inventory forces the reload of the inventory, which in the case of dynamic inventory scripts means they will be re-executed. This is mainly useful when additional hosts are created and users wish to use them instead of using the `add_host` module."

**Comment by hackermd** [comment]
The only way I currently see to parse the variable to `tm_inventory` without breaking its Ansible inventory functionality is via an environment variable. I've implemented it as follows:

- the path to the setup file (archfile) gets parsed to `tm_deploy` via the `-s` or `--setup-file` flag
- `tm_deploy` sets the environment variable `TM_SETUP` to the parsed value for the `subprocess`
- `tm_inventory` reads the value of the environment variable to dynamically build the inventory

See TissueMAPS/TmDeploy@18d904eefd4260c43ea84a547a7bcf71026f6ee5
